### ISSUE TITLE
添加一个进制转浮点的功能

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#103]
例如：
Hex -> IEEE 754浮点数
Float -> Hex

参考网站
http://www.speedfly.cn/tools/hexconvert/
![image](https://user-images.githubusercontent.com/25242380/228105937-41409df0-169f-45d7-b428-344a0e052ee9.png)

_Originally posted by @MrAccle in https://github.com/he3-app/he3-feedback/discussions/91_

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该功能已经增加，点击最新链接查看：https://t.he3app.com?3oro
![image](https://user-images.githubusercontent.com/68501045/230889165-343e6958-55f6-47dc-9014-b2bb844bf041.png)
