### ISSUE TITLE
希望AES加解密密钥和偏移量可以修改默认配置

### ISSUE THREAD

**Issue by haochenm** [he3-app/he3-community#105]
如题，经常加解密文件，密钥和偏移量都是相同的，每次都得重新修改默认配置的密钥和偏移量有点麻烦，能不能改成可配置的

**Comment by lyzhang1999** [comment]
感谢你的建议~
我们将支持工具的配置信息的同步，具体方法我确认后回复您。

**Comment by zhenweiwang1990** [comment]
你升级到最新版本，然后登录后，就可以自动记住工具的选项了。

**Comment by liuxzzz** [comment]
> 如题，经常加解密文件，密钥和偏移量都是相同的，每次都得重新修改默认配置的密钥和偏移量有点麻烦，能不能改成可配置的

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/129515480/229406729-d6952bbc-49fe-46ce-92a4-ddebf3bf511c.png">
升级至1.0.1版本已经支持记住密钥和偏移量。

**Comment by zhenweiwang1990** [comment]
点开这个就行了。 https://t.he3app.com?hfkq
