### ISSUE TITLE
产品bug

### ISSUE THREAD

**Issue by TopChina** [he3-app/he3-community#106]
升级以后点右侧导航不显示列表信息了,一片空白,但是可以搜索到小工具
Mac OS版本13.2.1 (22D68)
He3 版本1.3.1 (1.3.1)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/11971348/229405290-74466126-8757-437c-aaa5-0040894c92da.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/11971348/229405318-f886ff67-a266-4665-aae6-6448e0f5eed7.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/11971348/229405337-75b35368-22fa-4de7-91dd-5cf4f4d2e132.png">

**Comment by lyzhang1999** [comment]
感谢您的反馈，我们尽快确认和修复。

**Comment by 1026903031** [comment]
@TopChina 您好，该问题已在新版本 1.3.2 修复，很抱歉为影响您工具的使用，我们会努力将应用做的更加完善好用，感谢您的反馈 🌹
应用更新可在应用内按照引导更新，或者在官网上下载最新的链接 https://he3.app/
