### ISSUE TITLE
UUID 工具建议

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#108]
uuid生成后需要去掉横线，生产中使用的uuid都是去掉横线的。

来源：微信公众号留言

**Comment by Mashirowww** [comment]
![image](https://user-images.githubusercontent.com/106071315/229481863-f4b612b9-047a-4cf5-8a99-37b96433832c.png)
加了一个按钮来控制分割符 工具已publish
工具连接：https://t.he3app.com?1exr
