### ISSUE TITLE
request: xml 转 java bean

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#109]
希望加入：xml 转 java bean 工具。
来源：微信公众号留言

**Comment by congcongnalian** [comment]
ready to start

**Comment by congcongnalian** [comment]
![image](https://user-images.githubusercontent.com/68501045/229671957-60a3f9e3-a07f-4974-bb8b-ebf74b976e81.png)
![image](https://user-images.githubusercontent.com/68501045/229673056-0d2cc732-f77a-47b0-8560-ed03a4873a28.png)

**Comment by congcongnalian** [comment]
XML to JAVA Bean: https://t.he3app.com?kub2
