### ISSUE TITLE
【数字进制转换工具】

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#112]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/111

<div type='discussions-op-text'>

<sup>Originally posted by **suwia** April  3, 2023</sup>
### Version
base-conversion 1.0.0

### Environment
Mac v1.3.2

### What is expected?
希望对【数字进制转换工具】添加二进制的小数转换功能

### What is actually happening?

        

</div>

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！二进制的小数转换功能，并且还增加负数进制转换，点击最新链接查看：https://t.he3app.com?lxrv

![image](https://user-images.githubusercontent.com/68501045/230318213-5b750bfb-173c-49c2-8622-a1eda567af03.png)
![image](https://user-images.githubusercontent.com/68501045/230318323-25d39d81-31bf-45b9-a19d-209a893e1c99.png)
