### ISSUE TITLE
Text Diff功能中建议增加读取文件功能

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#119]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **gauson89** April  5, 2023</sup>
Text Diff功能中建议增加读取文件功能</div>

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了！已增加读取文件功能，可以前往最新的工具中体验哦～
link：https://t.he3app.com?aake
![image](https://user-images.githubusercontent.com/106071315/231099352-60858cdb-8d78-4b3e-88f9-3c94fc30a0e7.png)

**Comment by gauson89** [comment]
已经使用上了，多谢。

**Comment by Mashirowww** [comment]
😃好嘞 不客气！后续还有什么建议敬请提出 感谢！
