### ISSUE TITLE
标签页多开

### ISSUE THREAD

**Issue by kzxuan** [he3-app/he3-community#123]
希望可以支持单个工具的标签页多开功能。
👍

**Comment by congcongnalian** [comment]
很高兴您能对我们的产品提出建议，该功能在最新的版本中已经发布，下面是我们官网地址：https://he3.app/zh/ ，
您可以下载体验最新版本，并且欢迎您提出更多合理的建议与需求。
![20230510101227_rec_](https://github.com/he3-app/he3-feedback/assets/68501045/affa7a8e-3cb3-4f97-88ce-b30f27d715c3)
