### ISSUE TITLE
feat: json转义功能

### ISSUE THREAD

**Issue by liujunjie2009** [he3-app/he3-community#129]
手动编辑json场景下,存在json嵌套json字符串的场景,这个时候json字符串需要“\”转义,功能参考: https://www.json.cn/json/jsonzip.html
![image](https://user-images.githubusercontent.com/47965033/231376640-b65bc3dc-5ecf-4820-80c4-82f2f5f82ac0.png)

**Comment by lyzhang1999** [comment]
p2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by liujunjie2009** [comment]
good

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该功能已经增加。点击最新链接查看 JSON 转义： https://t.he3app.com?zne4
JSON 反转义：https://t.he3app.com?nq73
![image](https://github.com/he3-app/he3-feedback/assets/68501045/5871d6f7-6284-4d61-bd48-81b87beffeeb)
![image](https://github.com/he3-app/he3-feedback/assets/68501045/83ecbbc0-d6e1-434d-8001-ee1bc23ce9a2)
