### ISSUE TITLE
JSON路径输出的数据错误

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#137]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **gauson89** April 16, 2023</sup>
JSON路径功能通过JSON Path ：$..bicycle 输出的数据是错误的
![image](https://user-images.githubusercontent.com/96934391/232276696-f5be1667-d004-47d5-b149-6d3499d8a117.png)
</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该问题已经修复：https://t.he3app.com?c9yj
![image](https://user-images.githubusercontent.com/68501045/232699843-758dc6a4-e36f-4367-8ee4-a32946a3755f.png)
