### ISSUE TITLE
文本分析BUG提交-中文字符统计错误

### ISSUE THREAD

**Issue by newilux** [he3-app/he3-community#140]
使用文本分析功能统计汉字时，字数能正常统计，但是一个汉字在统计字符时候只算作一个字符，应该算作两个字符

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by Mashirowww** [comment]
您好！我们经过调研后得出的结论是，在文本分析领域中，一个中文汉字被视为一个字符，而不是两个字符。这意味着在进行文本分析时，我们会将每个中文汉字作为一个独立的单位来计算。

我们非常感谢您提供的反馈和信息，这对我们的沟通十分重要。我们将继续关注并适应最新的行业标准和实践，以确保我们在与用户沟通时提供准确且专业的信息。

如果您还有任何其他问题或需要进一步的讨论，请随时告诉我们。我们非常愿意与您保持沟通并提供帮助。谢谢！
