### ISSUE TITLE
RSA加密解密的小缺陷

### ISSUE THREAD

**Issue by cokyrain** [he3-app/he3-community#142]
RSA加密解密功能希望能补充：
公钥解密和私钥加密
![Could not convert private key from PEM; PEM header type is not "PRIVATE KEY" or "RSA PRIVATE KEY".](https://user-images.githubusercontent.com/75012356/232729426-277494f8-99fa-4a27-adf6-218ce301e1ed.jpg)
![Could not convert public key from PEM; PEM header type is not "PUBLIC KEY" or "RSA PUBLIC KEY".](https://user-images.githubusercontent.com/75012356/232729899-cd8d183a-c63e-449b-986b-2a25755a8521.jpg)

**Comment by lyzhang1999** [comment]
感谢反馈，我已经反馈给了产品部门，请关注这个 issues 的进度。

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by Mashirowww** [comment]
感谢您的反馈！我们非常重视用户的意见和建议。根据您提供的信息，我们经过调研并认识到在RSA加解密领域中，私钥加密公钥解密的方式被认为是无意义且存在安全风险。为了提供更安全可靠的解决方案，我们已经增加了私钥签名和公钥验证的模块，供您选择使用。您可以前往最新的工具中进行体验！
link：https://t.he3app.com?fifr
<img width="1316" alt="image" src="https://github.com/he3-app/he3-feedback/assets/106071315/5f530fea-f444-47e3-a68d-af54b5636a2e">
