### ISSUE TITLE
bug: Json to struct 对 时间类型的匹配不准确

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#157]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/156

<div type='discussions-op-text'>

<sup>Originally posted by **alctny** April 23, 2023</sup>
![json-to-struct类型推断不准确](https://user-images.githubusercontent.com/44720162/233817605-da6f983a-e2ed-4a37-9245-ba433773ad79.png)
</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该问题已经修复：https://t.he3app.com?qdiv
![image](https://user-images.githubusercontent.com/68501045/235125877-7b84412d-0dfa-4622-8171-c5d660458fa7.png)
