### ISSUE TITLE
About the bug of tool rsa-key-pair-generator

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#161]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **jesseincn** April 26, 2023</sup>
### Version
rsa-key-pair-generator 1.0.0

### Environment
Mac v1.3.2

### What is expected?
public key title error

### What is actually happening?
the title both Private Key

        

</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该问题已经修复，点击最新链接查看：https://t.he3app.com?sa7y
![image](https://user-images.githubusercontent.com/68501045/237058310-c3cab151-9180-46de-83fd-a592923e4a5a.png)
