### ISSUE TITLE
About the bug of tool hash

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#165]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **dubiao** April 28, 2023</sup>
### Version
hash 1.0.5

### Environment
Mac v1.3.2

### Steps to reproduce
input anything

### What is expected?
output all hash values

### What is actually happening?
nothing happens

        

</div>

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该问题已经修复，点击最新链接查看：https://t.he3app.com?d8c1
![20230512105458_rec_](https://github.com/he3-app/he3-feedback/assets/68501045/05a7edba-f846-4003-b780-008113e5f313)
