### ISSUE TITLE
增加JSON串双引号转义功能与反转义功能

### ISSUE THREAD

**Issue by zhanggang807** [he3-app/he3-community#170]
增加JSON串双引号转义功能与反转义功能
比如{\"age\":1}和{"age":1}之前相互转换
参考 [JSON转义](http://www.ab173.com/gongju/json/zhuanyi.php)

**Comment by lyzhang1999** [comment]
p1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该功能已经增加。点击最新链接查看 JSON 转义： https://t.he3app.com?zne4
JSON 反转义：https://t.he3app.com?nq73
![image](https://github.com/he3-app/he3-feedback/assets/68501045/5871d6f7-6284-4d61-bd48-81b87beffeeb)
![image](https://github.com/he3-app/he3-feedback/assets/68501045/83ecbbc0-d6e1-434d-8001-ee1bc23ce9a2)
