### ISSUE TITLE
URL 解码,不包含URL参数?

### ISSUE THREAD

**Issue by fengzidk** [he3-app/he3-community#181]
如图
![image](https://github.com/he3-app/he3-feedback/assets/22466765/b7fb252c-eeb9-447b-a58c-4ef4ff3ced47)

**Comment by lyzhang1999** [comment]
感谢您的反馈，我们已经确认了该问题。

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by lyzhang1999** [comment]
请尝试选择 URI Component 选项来解析参数

![img_v2_62c7797f-8c21-4ac7-a55b-ff992492405g](https://github.com/he3-app/he3-feedback/assets/8142348/b3aff6e1-f666-46c2-8307-2318bc987b55)

**Comment by fengzidk** [comment]
> 请尝试选择 URI Component 选项来解析参数
> 
> ![img_v2_62c7797f-8c21-4ac7-a55b-ff992492405g](https://user-images.githubusercontent.com/8142348/239178958-b3aff6e1-f666-46c2-8307-2318bc987b55.jpg)

好使,但是设计感觉有点怪异,建议把产品叼一顿
