### ISSUE TITLE
用Base64 图像/文件编码工具编码后样式直接顶到界面外

### ISSUE THREAD

**Issue by wukaipeng-dev** [he3-app/he3-community#196]
<img width="1429" alt="image" src="https://github.com/he3-app/he3-feedback/assets/68799055/9648ff9f-05ef-44a8-b96e-1ebd7094a624">

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该问题已经修复。点击最新链接：https://t.he3app.com?x996
![image](https://github.com/he3-app/he3-feedback/assets/68501045/2fb76e7f-33a7-4212-96c3-c8579a952b07)
