### ISSUE TITLE
缺少xml格式化功能

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#208]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/206

<div type='discussions-op-text'>

<sup>Originally posted by **MrAccle** May 29, 2023</sup>
目前有xml压缩功能
无xml格式化功能
功能参考网站：
https://c.runoob.com/front-end/710/</div>

**Comment by lyzhang1999** [comment]
P1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！该功能一直存在，您可以通过下面连接进访问： https://t.he3app.com?7xtr ，
在访问之前，请将您的本地客户端升到最新版本！
![image](https://github.com/he3-app/he3-feedback/assets/68501045/c838692a-e248-4bb3-b1e8-1cb7f519541d)
