### ISSUE TITLE
关闭剪贴板功能吧

### ISSUE THREAD

**Issue by TopChina** [he3-app/he3-community#210]
剪贴板里面有太多隐私,居然还有云同步功能,我最近都不敢打开he3软件了

**Comment by lyzhang1999** [comment]
感谢您的建议，我们将评估这个问题。

**Comment by lyzhang1999** [comment]
P1

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P1，请留意 issues 进度。

**Comment by congcongnalian** [comment]
非常高兴您能提出反馈！在最新版本中，该问题已经修复，您可以更新到最新的客户端进行体验。
![20230605101904_rec_](https://github.com/he3-app/he3-feedback/assets/68501045/0ec78f68-1a38-41e2-975e-fad5f4729ac0)
