### ISSUE TITLE
jwt 生成器，工具样式问题

### ISSUE THREAD

**Issue by zhangze-github** [he3-app/he3-community#229]
<img width="990" alt="image" src="https://github.com/he3-app/he3-feedback/assets/41512027/01c427f8-75d1-47aa-ad23-39e379c00839">

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by zhangze-github** [comment]
fixed
