### ISSUE TITLE
登录后不能正常显示头像

### ISSUE THREAD

**Issue by EyoungShieh1992** [he3-app/he3-community#236]
![image](https://github.com/he3-app/he3-feedback/assets/31103392/658756bf-3fbf-4dad-bade-cc462d96a4e5)

退出登录后，再重新登录问题依旧

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by zhangze-github** [comment]
fixed

**Comment by ye4241** [comment]
问题依旧，用的Github登录的。
![image](https://github.com/he3-app/he3-feedback/assets/6803102/3e03dc50-0c57-47bd-a6c6-9ea4454d7798)

网页版头像正常
![image](https://github.com/he3-app/he3-feedback/assets/6803102/4f84b5bf-2b64-4ecc-b9e7-ca4265527953)
