### ISSUE TITLE
[bug]文本分析工具-词汇统计有误

### ISSUE THREAD

**Issue by wukaipeng-dev** [he3-app/he3-community#243]
<img width="1280" alt="image" src="https://github.com/he3-app/he3-feedback/assets/68799055/9f260d51-6130-433f-b21e-ac2d334dcbe7">

这里应该是 6 个单词

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by zhangze-github** [comment]
fixed
