### ISSUE TITLE
XML压缩器 - Bug Report

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#245]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **MrAccle** July 19, 2023</sup>
xml的压缩后丢失关闭标签

压缩前：
![image](https://github.com/he3-app/he3-feedback/assets/25242380/3ec5c2ec-ec26-4846-ad1f-9eb2a83fd4ea)

压缩后：
![image](https://github.com/he3-app/he3-feedback/assets/25242380/3c776885-5c99-4189-b34c-7ca5f3eeda02)
![image](https://github.com/he3-app/he3-feedback/assets/25242380/4261832a-4176-4a27-b0fa-409272fbcb4a)
</div>

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by yinjg1997** [comment]
## fixed
#### 压缩前
![image](https://github.com/he3-app/he3-feedback/assets/115864743/edaf12b5-0c29-4017-b22c-761e647648cc)
#### 压缩后
![image](https://github.com/he3-app/he3-feedback/assets/115864743/36f6b911-3fff-432a-9e6d-5afe7a50e17f)
