### ISSUE TITLE
Json压缩器Long类型精度丢失

### ISSUE THREAD

**Issue by vince-0202** [he3-app/he3-community#251]
<img width="1044" alt="image" src="https://github.com/he3-app/he3-feedback/assets/48322565/5bfa5d4e-2e63-4b03-9d23-dca9992245da">

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by yinjg1997** [comment]
fixed
![image](https://github.com/he3-app/he3-feedback/assets/115864743/378d3c68-196a-47c5-b546-784cfa32c087)
