### ISSUE TITLE
Hex转Base64输出数据错误

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#253]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **gauson89** August  5, 2023</sup>
![image](https://github.com/he3-app/he3-feedback/assets/96934391/cae90a34-d79e-464b-9e3c-27cf7e6468fc)
</div>

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by yinjg1997** [comment]
fixed

![image](https://github.com/he3-app/he3-feedback/assets/115864743/ecc84978-5bd9-4ae8-a811-0e63ca8db979)
