### ISSUE TITLE
官网没有安装包的下载地址

### ISSUE THREAD

**Issue by weiwill** [he3-app/he3-community#268]
![image](https://github.com/he3-app/he3-feedback/assets/3794090/f7ddecc6-ec23-4d2e-9da2-06b5da8720ae)

**Comment by lyzhang1999** [comment]
抱歉，我们将尽快修复，你可以先前往 https://he3.app/zh 下载。

Mac：
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_mac_arm64_1.3.23.dmg
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_mac_x64_1.3.23.dmg

Win：
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_windows_installer_x64_1.3.23.exe
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_windows_installer_ia32_1.3.23.exe

Linux：
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_linux_arm64_1.3.23.deb
https://he3-1309519128.cos.accelerate.myqcloud.com/1.3.23/He3_linux_amd64_1.3.23.deb

![image](https://github.com/he3-app/he3-feedback/assets/8142348/d052abb8-73e7-4910-b2d9-4724006c5f38)

**Comment by weiwill** [comment]
已下，谢谢
