### ISSUE TITLE
ObjectId to Date

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#293]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/292

<div type='discussions-op-text'>

<sup>Originally posted by **alctny** October 21, 2023</sup>
希望能够添加可以从 MongoDB 的 ObjectId 中分离出时间信息，比如转化成 timestamp 或者 date 之类的其他人类可读时间格式

可参考对象：
[MongoDB ObjectId ↔ Timestamp Converter](https://steveridout.com/mongo-object-time/)</div>

**Comment by lyzhang1999** [comment]
P2

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P2，请留意 issues 进度。

**Comment by yinjg1997** [comment]
Added
![image](https://github.com/he3-app/he3-feedback/assets/115864743/f57064f4-f595-4b36-957b-ccc9a7a42bcb)
