### ISSUE TITLE
About the bug of tool uuid-parser

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#300]
### Discussed in https://github.com/he3-app/he3-feedback/discussions/299

<div type='discussions-op-text'>

<sup>Originally posted by **ctyytc** October 31, 2023</sup>
### Version
uuid-parser 1.0.5

### Environment
Mac v2.0.0

### Steps to reproduce
Open the tool

### What is expected?
Can work

### What is actually happening?
Can't work, nothing to see.

        

</div>

**Comment by lyzhang1999** [comment]
P0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by zhangze-github** [comment]
fixed, 请点击工具右上角升级一下工具
![image](https://github.com/he3-app/he3-feedback/assets/41512027/d79e93eb-38d6-432a-98ef-8f86c8f1e6a3)

**Comment by zhangze-github** [comment]
fixed
