### ISSUE TITLE
大家注意 he3会偷偷下载更新文件

### ISSUE THREAD

**Issue by clfsoft** [he3-app/he3-community#325]
在下面这个目录
AppData\Local\he3-updater\pending

敢偷偷下载，未必不敢偷偷上传东西。

**Comment by clfsoft** [comment]
等着看官方会不会删除这个issue

**Comment by lyzhang1999** [comment]
下载自动更新所需要的文件不是很正常么。。

**Comment by clfsoft** [comment]
问题我没有设置自动更新啊 about 里头红点提醒有新版本还不够，
你自动给我下载一份。下载完还要求管理员权限更新。
本来这个东西要login就已经够狠了，吃相在哪里啊。

**Comment by lyzhang1999** [comment]
别用了，卸载吧。

**Comment by clfsoft** [comment]
已经卸载。在这里提醒其他人不要用。毕竟存在不小的安全隐患。
[官方文档](https://he3.app/zh/blogs/update-1219/)
 **2. 流畅的新版本更新**
**当有新版本时会自动提示更新并帮助您快速下载**

上面的描述是帮助你快速下载，而不是自动帮我下载。

本来提醒有新版本，about 里头有下载链接很完美了。
偏偏偷偷自动下载+自动更新，关键最大的问题是它要管理员权限更新。
