### ISSUE TITLE
json 序列化会把long 的精度截断??

### ISSUE THREAD

**Issue by ggbala** [he3-app/he3-community#84]

**Comment by hongchaodeng** [comment]
非常抱歉。这个问题我们会尽快修复！

**Comment by ggbala** [comment]
感谢
| |
鉏飞祥
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Hongchao ***@***.***> |
| 发送日期 | 2023年3月27日 10:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [he3-app/he3-feedback] json 序列化会把long 的精度截断?? (Issue #84) |

非常抱歉。这个问题我们会尽快修复！

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了！问题已解决，可以前往最新的工具中体验～
link：https://t.he3app.com?5p3h
![image](https://user-images.githubusercontent.com/106071315/230816292-9a043a0e-9ec0-49fa-928f-bf54cd13c4a4.png)

**Comment by ggbala** [comment]
感谢感谢
