### ISSUE TITLE
【需求】大佬，多会可以支持插件

### ISSUE THREAD

**Issue by plusgua** [he3-app/he3-community#86]
大佬可以加个功能，JavaScript/typescript 写模块

比如，点添加按钮，然后输入名称，注释，以及代码，完成页面绘制+数据操作，点保存后，页面就多一个模块

**Comment by zhenweiwang1990** [comment]
很快了，预计我们3月底，或者4月初会开放这一能力，如果你感兴趣，可以申请我们的早期试用。我们会允许用户写一个 vue 组件来快速添加一个自己的工具。

**Comment by hongchaodeng** [comment]
内测报名开始了: https://github.com/he3-app/he3-feedback/discussions/88

**Comment by zhenweiwang1990** [comment]
目前最新版本已经支持开发者自行扩展了，请看：  https://docs.he3app.com/guide/
