### ISSUE TITLE
[微信群] 调整图片大小工具在压缩大图片时报错

### ISSUE THREAD

**Issue by lyzhang1999** [he3-app/he3-community#95]
![3](https://user-images.githubusercontent.com/8142348/228508669-194dc6dd-9a17-4ef1-802c-d4ec26b9ef02.jpg)

![image](https://user-images.githubusercontent.com/8142348/228508731-69cb4967-5240-401f-9c20-da13172b3bfc.png)

工具：图片调整大小
表现：点击压缩后卡死
控制台错误信息：见截图
反馈用户：微信群，来死去的深渊中进化一只折耳熊

**Comment by lyzhang1999** [comment]
p0

**Comment by lyzhang1999** [comment]
感谢您的反馈，产品部门正在加紧处理，优先级为P0，请留意 issues 进度。

**Comment by Mashirowww** [comment]
让您久等了！问题已解决，可以前往最新版本的工具中体验
https://t.he3app.com?image-resizer
![image](https://user-images.githubusercontent.com/106071315/230819346-3174302e-c4c8-499b-af6e-585f651757cd.png)
